import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Generated App",
  description: "Generated by Flake AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <script dangerouslySetInnerHTML={{ __html: "window.addEventListener('load', () => { const scrollWidth = document.documentElement.scrollWidth; const clientWidth = document.documentElement.clientWidth; if (scrollWidth > clientWidth) { console.error('Validation Error: Horizontal overflow detected. scrollWidth (' + scrollWidth + ') > clientWidth (' + clientWidth + ')'); } });" }} />
      </body>
    </html>
  );
}